const MODULES=[
["Understanding Phishing","Phishing is a fake message that pretends to be a trusted company to trick you into sharing private information.","An email “from your bank” links to a look-alike login page.","Urgent tone|Generic greeting|Slightly misspelt web address","Type the official address yourself or use the official app.","Enter passwords after clicking an email link.","A link opens a login page with a slightly misspelt address. What now?","Log in quickly|Close it and visit the official site directly|Reply asking if it is real",1,"Going to the official site yourself avoids look-alike pages."],
["Recognising Suspicious SMS Messages","Scam texts use pressure and unknown links to make you act before thinking.","“Your KYC has expired, click example-link.”","Threats of suspension|Odd or shortened links|Unknown sender","Check the official app.","Tap links in unexpected texts.","A text says your account closes today unless you tap a link.","Tap it|Check in your bank’s official app|Forward it to friends",1,"Official apps show real alerts without risky links."],
["WhatsApp & Messaging Scams","Scammers may pose as friends, relatives or officials from new numbers.","“Hi Mum, this is my new number, please send money.”","New number claiming to be family|Money requests|Asks you to keep it secret","Call the person on their known number.","Send money before verifying.","A “relative” from a new number asks for money.","Send money|Call their old number to check|Share bank details",1,"A quick call confirms who is really writing."],
["OTP & Account Security","An OTP is a private key for one action. Anyone asking for it wants access.","“I am from support, please read the code just sent.”","Caller asks for an OTP|Says it is for “verification”|Pressure","Keep OTPs private, always.","Read codes out to anyone.","A “support agent” asks for the OTP you just received.","Share it|Hang up and contact support officially|Share half of it",1,"Genuine services do not need you to disclose OTPs."],
["Fake Websites","Fake sites copy real ones to collect logins or payments.","A look-alike store copies a famous shop’s design.","Odd web address|Prices far too low|Transfer-only payment","Check the address before paying.","Trust a site only because it looks professional.","A site sells a phone at 80% off, transfer-only payment.","Buy quickly|Skip it and use a trusted store|Pay half",1,"Extreme discounts plus unusual payment are classic signs."],
["Online Shopping Scams","Fake sellers take payment and never deliver.","A new social media “store” with no reviews wants advance payment.","Advance payment only|No return policy|Brand-new account","Prefer protected payment methods.","Pay strangers by personal transfer.","A seller insists on advance payment to a personal account.","Pay|Choose a protected payment method or another seller|Send a small test amount",1,"Protected payments give you a way to dispute problems."],
["Job & Recruitment Scams","Real employers do not charge you to hire you.","“Pay a registration fee to confirm your job offer.”","Fees for hiring|Offers with no interview|Chat-only hiring","Research the company independently.","Pay to get a job.","A recruiter asks for a fee to “reserve” your job.","Pay it|Decline and verify the company|Send ID copies first",1,"Asking candidates to pay is a strong warning sign."],
["Investment Scams","Scams promise high, guaranteed returns with little risk.","“Double your money in 7 days, guaranteed.”","Guaranteed returns|Pressure to invest fast|Unregistered advisers","Check registration with official regulators.","Trust screenshots of profits.","A group promises guaranteed 40% monthly returns.","Invest now|Be sceptical, since real investments carry risk|Invite friends",1,"No honest investment can guarantee high returns."],
["Social Engineering","Scammers manipulate emotions such as fear, greed and kindness rather than hacking devices.","A caller pretends to be a manager needing “urgent” help.","Emotional pressure|Authority claims|Asks to skip normal steps","Pause and verify who is asking.","Skip checks because someone sounds important.","A “manager” messages you to buy gift cards urgently.","Do it fast|Verify through a known contact|Keep it secret",1,"Verification breaks the pressure scammers rely on."],
["What To Do After a Scam","Acting quickly can limit harm, and being targeted is not your fault.","You shared a card number by mistake.","Unexpected transactions|Locked accounts|Passwords stop working","Contact your bank through official channels and change passwords.","Hide it or send money to “recover” funds.","You shared card details with a stranger. First step?","Wait and see|Contact your bank via its official channel|Call the number in the message",1,"Banks can block cards fast when told early."]];
const QS=[
["A message says your account will be blocked in 10 minutes unless you click a link. What should you do?","Click immediately|Share the OTP|Verify through the official app or website|Forward the message",2,"Urgency is a pressure tactic. Verify independently."],
["Which password habit is safest?","Reuse one strong password|Use unique passwords, ideally with a password manager|Use your birthday|Write it in chat to yourself",1,"Unique passwords stop one leak from opening many accounts."],
["A caller asks for the OTP “to cancel a payment”. You…","Read it out|Refuse and end the call|Read half|Send it by text",1,"OTPs must stay private."],
["To receive money by UPI, you need to…","Enter your PIN|Approve every request|Share nothing; receiving needs no PIN|Scan any QR code",2,"A PIN is only for sending money."],
["Which link is most suspicious?","The address typed from your bank card|A shortened link in an unexpected text|A link in the official app|A bookmark you made",1,"Shortened links hide the destination."],
["A shop site offers 85% off and accepts only bank transfer. This is…","A great deal|Likely a fake store|Safe if the site looks good|Fine for small orders",1,"Extreme discounts plus unusual payment are red flags."],
["A “manager” messages for urgent gift cards and says keep it private. This is…","Normal|Social engineering|A test of loyalty|Safe if polite",1,"Secrecy and urgency are classic manipulation."],
["Before buying from a new seller, you should…","Pay in advance|Check reviews and use protected payment|Trust the photos|Skip the return policy",1,"Protected payment and reviews reduce risk."],
["A WhatsApp contact from a new number asks for money. First…","Send a small amount|Call them on their old number|Ask for a selfie|Ignore everything forever",1,"A call to a known number confirms identity."],
["Someone says you’ve won a prize you never entered. You should…","Pay the fee|Ignore or verify independently|Share ID|Reply quickly",1,"Real prizes do not require you to pay first."]].map(([q,o,a,w])=>({q,o:o.split("|"),a,w}));
const SC=[
["SMS: “Your bank KYC has expired. Update now: http://example-bank-kyc.invalid”","A message like this arrives. What would you do?","Click the link|Reply to the message|Verify through the official app or website|Share the OTP",2,"Scammers create urgency so you act before verifying."],
["The sender is an ordinary mobile number, not a known contact.","How should this affect your trust?","It is a warning sign; verify independently|It makes it official|It has no effect|Reply to ask who they are",0,"Unexpected senders claiming to be your bank deserve caution."],
["It says your account will be suspended in 2 hours.","How do you treat the deadline?","Act fast|Treat the pressure as a warning sign and pause|Forward it to friends|Pay to avoid suspension",1,"Artificial deadlines are a pressure tactic."],
["A page from the link asks for card number, PIN and OTP.","What do you do?","Enter everything|Close the page and never share PIN or OTP|Enter only the OTP|Enter a fake PIN",1,"Legitimate pages never need your PIN and OTP together."],
["You tapped the link but entered nothing.","What is the best next step?","Close it and check your account in the official app|Enter details to be safe|Reply STOP|Ignore it forever",0,"Closing the page and checking officially is calm and safe."]].map(([c,q,o,a,w])=>({ctx:c,q,o:o.split("|"),a,w}));
const GM=[["Congratulations!",0],["You have won a ₹50,000 reward.",1,"Unexpected prize"],["Claim within 15 minutes.",1,"Urgency"],["Click here: http://prize-claim.example.invalid",1,"Suspicious link"],["Reply with your card number to receive it.",1,"Request for information"],["— Rewards Team",0]];
const $=s=>document.getElementById(s);
function runQuiz(el,qs,end){let i=0,sc=0;const show=()=>{const q=qs[i];
el.innerHTML=`<p class="small text-info mb-1">Question ${i+1} of ${qs.length}</p>${q.ctx?`<div class="sms mb-3">${q.ctx}</div>`:""}<h3 class="h5">${q.q}</h3><div class="d-grid gap-2 my-3">${q.o.map((o,k)=>`<button class="btn btn-outline-info text-start" data-k="${k}">${"ABCD"[k]}. ${o}</button>`).join("")}</div><div aria-live="polite" data-fb></div>`;
el.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{const ok=+b.dataset.k==q.a;if(ok)sc++;
el.querySelectorAll("[data-k]").forEach(x=>{x.disabled=true;if(+x.dataset.k==q.a)x.className="btn btn-success text-start"});if(!ok)b.className="btn btn-warning text-start";
el.querySelector("[data-fb]").innerHTML=`<div class="alert alert-${ok?"success":"info"}"><b>${ok?"Correct!":"Not quite."}</b> Why? ${q.w}</div><button class="btn btn-neon" data-nx>${i+1<qs.length?"Next Step":"Finish"}</button>`;
el.querySelector("[data-nx]").onclick=()=>{++i<qs.length?show():end(sc)}})};show()}
const again=`<button class="btn btn-outline-info mt-2" onclick="location.reload()">Try again</button>`;
if($("quiz"))runQuiz($("quiz"),QS,sc=>{CS.set(d=>d.quizzes.push(sc));$("quiz").innerHTML=`<h3>Your Score: ${sc}/${QS.length}</h3><p>${sc>=8?"Great job! You correctly identified most common scam warning signs.":"Good effort! Review the learning modules and try again."}</p>${again}`});
if($("scen"))runQuiz($("scen"),SC,sc=>{CS.set(d=>d.scenario=Math.max(d.scenario,sc));$("scen").innerHTML=`<h3>Scenario Complete</h3><p>You identified ${sc}/5 warning signs.</p><p><b>Key lesson:</b> Pause → Verify → Protect</p>${again}`});
if($("game")){let f=0,w=0,tot=GM.filter(x=>x[1]).length;$("game").innerHTML=`<p>Tap the suspicious parts of this fictional message.</p><div class="sms mb-3">${GM.map((x,i)=>`<button class="tok" data-i="${i}">${x[0]}</button>`).join(" ")}</div><p aria-live="polite" id="gs">Found 0/${tot}</p>`;
$("game").onclick=e=>{const b=e.target.closest("[data-i]");if(!b||b.classList.contains("good")||b.classList.contains("bad"))return;const x=GM[b.dataset.i];
if(x[1]){b.classList.add("good");b.insertAdjacentHTML("beforeend",` <small>(${x[2]})</small>`);f++}else{b.classList.add("bad");w++}
const pts=Math.max(0,f*3-w);$("gs").textContent=`Found ${f}/${tot} · Points: ${pts}`+(f==tot?" · Well done! Pause → Verify → Protect":"");if(f==tot)CS.set(d=>d.game=Math.max(d.game,Math.min(10,pts)))}}
if($("mods")){const d=CS.get();$("mods").innerHTML=MODULES.map((m,i)=>`<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#c${i}">Module ${i+1}: ${m[0]} ${d.modules.includes(i)?'<i class="bi bi-check-circle-fill text-success ms-2"></i>':""}</button></h2><div id="c${i}" class="accordion-collapse collapse" data-bs-parent="#mods"><div class="accordion-body"><p>${m[1]}</p><div class="sms mb-3"><b>Example:</b> ${m[2]}</div><h3 class="h6">Warning signs</h3><ul>${m[3].split("|").map(x=>`<li>${x}</li>`).join("")}</ul><div class="row g-2 mb-3"><div class="col-md-6"><div class="alert alert-success mb-0"><i class="bi bi-check-lg"></i> <b>Do:</b> ${m[4]}</div></div><div class="col-md-6"><div class="alert alert-danger mb-0"><i class="bi bi-x-lg"></i> <b>Don’t:</b> ${m[5]}</div></div></div><h3 class="h6">Mini quiz</h3><div id="mq${i}" class="glass mb-3"></div><button class="btn btn-neon" id="done${i}">${d.modules.includes(i)?"Completed ✓":"Mark as complete"}</button></div></div></div>`).join("");
MODULES.forEach((m,i)=>{runQuiz($("mq"+i),[{q:m[6],o:m[7].split("|"),a:m[8],w:m[9]}],sc=>{$("mq"+i).innerHTML=`<p class="mb-0">${sc?"Nice work!":"Good try."} Key lesson: Pause → Verify → Protect.</p>`});
$("done"+i).onclick=e=>{CS.set(d=>{if(!d.modules.includes(i))d.modules.push(i)});e.target.textContent="Completed ✓"}});
if(location.hash){const t=document.querySelector(location.hash.replace("#m","#c"));t&&new bootstrap.Collapse(t,{toggle:true})}}
