const SCAMS=[
{id:"kyc",n:"Fake Bank KYC Message",cat:"sms",ch:"SMS",risk:"High",m:"Your bank account KYC has [[expired]]. [[Update immediately to avoid account suspension]]. Click here: [[http://example-bank-kyc.invalid]]",s:["Urgency","Threat of account closure","Unknown link","Hidden request for sensitive information"],w:"Login details, card numbers, OTPs",r:"Do not click. Open your bank’s official app or website yourself, or call the number printed on your card."},
{id:"wa",n:"“New Number” Family Request",cat:"whatsapp",ch:"WhatsApp",risk:"Medium",m:"Hi Mum, this is my [[new number]]. My phone broke. [[Can you send money urgently]]? I will explain later.",s:["Claims a changed number","Emotional pressure","Money request","Avoids a voice call"],w:"Money transfers",r:"Call your relative on their saved number before doing anything."},
{id:"mail",n:"Fake Account Login Alert",cat:"email",ch:"Email",risk:"High",m:"Dear Customer, unusual sign-in detected. [[Verify within 24 hours]] or your account will be [[locked]]: [[http://example-login-check.invalid]]",s:["Generic greeting","Deadline","Look-alike link"],w:"Usernames and passwords",r:"Go to the real site by typing its address, then check account alerts there."},
{id:"upi",n:"“Collect Request” Refund Trick",cat:"banking",ch:"UPI app",risk:"High",m:"We will refund your payment. [[Approve the request and enter your PIN]] to receive money. — Refund Desk (fictional)",s:["PIN needed to receive money","Unexpected refund","Pressure to approve"],w:"UPI PIN, money",r:"You never need a PIN to receive money. Decline and report the request in your app."},
{id:"job",n:"Pay-to-Work Job Offer",cat:"job",ch:"Chat / Email",risk:"Medium",m:"You are selected! Earn [[₹5,000 daily]] from home. Pay a [[refundable registration fee]] to start.",s:["No interview","Unrealistic pay","Fee to get hired"],w:"Fees and ID documents",r:"Research the company independently. Real employers do not charge to hire you."},
{id:"shop",n:"Too-Good-To-Be-True Online Store",cat:"shopping",ch:"Social media ad / Website",risk:"Medium",m:"Brand phones at [[80% OFF]]! [[Only 3 left]]. Pay by [[direct transfer]] at example-deals.invalid",s:["Extreme discount","Fake scarcity","Transfer-only payment"],w:"Payments, card details",r:"Use trusted stores, check reviews, and prefer protected payment methods."},
{id:"inv",n:"Guaranteed Returns Scheme",cat:"investment",ch:"Messaging groups",risk:"High",m:"Join our group. [[Guaranteed 40% monthly returns]], zero risk. [[Limited seats]] — invest today!",s:["Guaranteed returns","Zero-risk claim","Pressure to join fast"],w:"Deposits and personal details",r:"Real investments carry risk. Check adviser registration with official regulators."},
{id:"soc",n:"Celebrity Giveaway Account",cat:"social",ch:"Social media",risk:"Low",m:"I am giving away prizes! [[Follow, send a DM]], then [[pay a small delivery fee]]. (fictional account)",s:["Unverified account","Fee for a “free” prize"],w:"Small payments, contacts",r:"Ignore, block, and report the account."},
{id:"sup",n:"Fake Customer Support Number",cat:"support",ch:"Search results / Calls",risk:"High",m:"Support: Install [[remote access app]] so we can fix your refund. Call [[000-000-0000]] (fictional).",s:["Unsolicited help","Remote access request","Number from an unofficial source"],w:"Device control, bank access",r:"Use contact details from the company’s official site or app only. Never install apps on a caller’s request."},
{id:"otp",n:"“Wrong Transfer” OTP Request",cat:"banking",ch:"SMS / Call",risk:"High",m:"Sorry, I sent money to you by mistake. [[Share the code]] you just received so I can cancel it.",s:["Stranger asks for a code","Friendly story","OTP request"],w:"OTP codes",r:"Never share OTPs. Tell the bank about the transfer through official channels."}];
const hl=t=>t.replace(/\[\[(.+?)\]\]/g,"<mark>$1</mark>");
const rc=r=>({High:"danger",Medium:"warning",Low:"success"})[r];
const list=document.getElementById("list");
if(list){let f="all";const q=document.getElementById("q");
const draw=()=>{const v=q.value.toLowerCase();const r=SCAMS.filter(s=>(f=="all"||s.cat==f)&&(s.n+s.ch+s.w).toLowerCase().includes(v));
list.innerHTML=r.map(s=>`<div class="col-md-6 col-lg-4"><div class="glass"><span class="badge text-bg-${rc(s.risk)} mb-2">${s.risk} risk</span><h3 class="h5">${s.n}</h3><p class="small text-secondary mb-1"><i class="bi bi-broadcast"></i> ${s.ch}</p><p class="small">Scammers want: ${s.w}</p><a class="btn btn-sm btn-neon" href="scam-details.html?id=${s.id}">View details</a></div></div>`).join("")||`<p class="text-secondary">No scams match. Try a different word or filter.</p>`};
document.getElementById("flt").onclick=e=>{const b=e.target.closest("[data-f]");if(!b)return;f=b.dataset.f;document.querySelectorAll("[data-f]").forEach(x=>x.classList.toggle("active",x==b));draw()};
q.oninput=draw;draw()}
const det=document.getElementById("detail");
if(det){const s=SCAMS.find(x=>x.id==new URLSearchParams(location.search).get("id"));
det.innerHTML=s?`<h1 class="h2">${s.n}</h1><span class="badge text-bg-${rc(s.risk)}">${s.risk} risk</span> <span class="badge text-bg-secondary">${s.ch}</span><p class="mt-3 mb-1 text-secondary">Fictional example (suspicious parts highlighted):</p><div class="sms mb-4">${hl(s.m)}</div><div class="row g-3"><div class="col-md-4"><div class="glass"><h2 class="h6">Warning signs</h2><ul>${s.s.map(x=>`<li>${x}</li>`).join("")}</ul></div></div><div class="col-md-4"><div class="glass"><h2 class="h6">What scammers try to get</h2><p>${s.w}</p></div></div><div class="col-md-4"><div class="glass"><h2 class="h6">How to respond</h2><p>${s.r}</p></div></div></div>`:`<p>Scam not found. <a href="scams.html">Back to library</a></p>`}
